lesson1をやりました
OZPA/html-css-study pull request #45
Opened 2019-08-16 11:36 UTC by nobukoni

index.htmlの通りにstyle.cssを修正しました。
レビューをお願いします！

2019-08-16 12:25 UTC, OZPA requested changes
styleに関しては完璧です！

インデントを半角スペース4つから2つにして下さい〜
（css界隈では2つが一般的です）
@nobukoni

2019-08-19 09:07 UTC, nobukoni commented
Indentをスペース2つに修正しました

2019-08-19 09:17 UTC, OZPA commented
OKです！
vs code周りの環境設定でなんか不要なファイルできてるっぽいですね。ちょっと環境設定覗いてみて下さい！わかんなければみますー

コードはLGTM
![3133d629](https://user-images.githubusercontent.com/3537277/63253863-9ebfa000-c2ad-11e9-884b-4272300d4204.gif)

2019-08-20 02:33 UTC, OZPA commented
LGTM!
![EErV5Fl](https://user-images.githubusercontent.com/3537277/63313084-4b496280-c33e-11e9-959f-17bb4c0449fd.gif)

2019-08-20 02:33 UTC, closed without merging